### ISSUE TITLE
Missing plugin configuration for dialog size

### ISSUE THREAD

**Issue by ogrish55** [AlexGirardDev/HarpoonIJ#1]
https://github.com/AlexGirardDev/HarpoonIJ/blob/master/src/main/java/ca/alexgirard/harpoonIJ/HarpoonDialog.java
Being able to override the setSize function at line 16 from plugin configuration settings would be a nice enhancement to this plugin.

**Comment by AlexGirardDev** [comment]
Hey, 

I have added options to change the dialog size, and font size in the newest version of the plugin

It should be approved and available within the next 1-2 days
