### ISSUE TITLE
Feature - Improved File Identification 

### ISSUE THREAD

**Issue by DavidAskwith** [AlexGirardDev/HarpoonIJ#13]
I'm a daily user of the plugin and it has greatly improved my workflow!

I frequently work on files that are deeply nested in a project. Files being displayed with long similar file paths make quick identification and organization of files difficult. 

Files displayed in other contexts within the IDE solve this issue by prepending the file path with the name of the file.

<img width="458" alt="image" src="https://github.com/AlexGirardDev/HarpoonIJ/assets/20693342/465eade9-46e3-4616-8cb3-353a1448e138">

This could be implemented in a simpler way than in other areas of the IDE by including the file name in parenthesis before the path.
`(index.php) /home/php/something/index.php`

I would be happy to do the work for this if you would like to see it added to the plugin.

**Comment by AlexGirardDev** [comment]
hmm, something like this would be nice.
The only issue / thing i'm not sure how to solve is that currently the modal popup is actualy just a text field that lets you edit the file names  / paths manually.

I am not sure how that would work easily / intuitevly if your list now looks something like 

(index.php) /home/php/something/index.php
(contact.php) /home/php/something/contact.php

**Comment by AlexGirardDev** [comment]
I am going to close this for now, If someone wants to create an alternative modal popup that accomplishes this I would be open to discussing that / a PR but for the time being i think the modal currently works for most use cases.
