### ISSUE TITLE
Open files in the same tab instead of creating multiple for harpoon files.

### ISSUE THREAD

**Issue by SpacRocket** [AlexGirardDev/HarpoonIJ#16]
Considering that a list of files available for harpoon to fetch is visible in dialogue box. It would be nice to have an option in settings to avoid creation of a new tab when file is fetched and not already displayed by tab.

**Comment by AlexGirardDev** [comment]
Hmm, currently I let jetbrains handle all of this for me. I  just have a reference to the virtual file that I got from the IDE and then call open on it when requested and it handles how to open the file.

I did some brief googling and found [this](https://youtrack.jetbrains.com/issue/IJPL-138476/Display-newly-opened-files-in-the-same-tab)which seems somewhat related but i'm not sure the current status of it or if this is even the same system.

Unfortunatly this is not a fetaure I would be interested in personally and I don't have much time to work on this project at the moment.

I would be open to a PR if you or someone else intereted in this feature wants to submit one though.

**Comment by AlexGirardDev** [comment]
closing for now

**Comment by SpacRocket** [comment]
Thank you Alex for your tips. It just came to my mind as possible improvement and thought that maybe there would be interest around it.

If I find some time I will reopen issue and do PR but as for now closing is a good idea.

Btw. Thanks for creating the plugin it makes my work more pleasurable every day!
