### ISSUE TITLE
Insert mode is set default on Harpoon dialog and cannot be configured

### ISSUE THREAD

**Issue by zleitz** [AlexGirardDev/HarpoonIJ#2]
When opening the harpoon dialog, the default mode is set to insert mode, so you have to exit insert mode to do any VIM movements when traversing the list, afaik, this isn't how it is in the normal Harpoon vim plugin. Proposal to let this be configurable via settings.

**Comment by AlexGirardDev** [comment]
I spent a couple hours trying to get this working the way you mentioned without any luck.

From my understanding I think the idea Vim plugin defaults all of the textboxes / text editors outside of the main code ones to insert mode as normally you would want it to work this way if your entering a name to refactor or something like that.

I may go over to there repo and ask them if there is a way to override this though as i do find this annoying myself.

**Comment by AlexGirardDev** [comment]
For reference https://github.com/JetBrains/ideavim/discussions/639

**Comment by HolbyFPV** [comment]
Would really love to see this.  

Additionally, the neovim plugin allows you to switch to a file by pressing enter.  When I click enter in the intelij dialog box it goes to the next line.  Can you support <CR> mapping to open the file under cursor instead of going to next line?

**Comment by AlexGirardDev** [comment]
@notblam i tried what was sugested a little bit but had some issues getting the ideavim plugin to actualy load within my plugin.

Everytime i tried to call the VimPlugin Api i was just get class not found exceptions.

I don't have any time right now to dig into this further but i may in the coming weeks.

**Comment by HolbyFPV** [comment]
> @notblam i tried what was sugested a little bit but had some issues getting the ideavim plugin to actualy load within my plugin.
> 
> Everytime i tried to call the VimPlugin Api i was just get class not found exceptions.
> 
> I don't have any time right now to dig into this further but i may in the coming weeks.

I added a comment with the last thing I was trying before I gave up.  I too was stuck with the ClassNotFound exception despite everything looking normal and the IDE finding things completely fine.  

I'll be on the lookout for your update :)

**Comment by bedware** [comment]
Hello, fellows! @AlexGirardDev, actually great job, thanks for the plugin. I used the plugin a lot in nvim. I can assume your implementation is the best at this moment. But after starting using it I found it quite annoying that the cursor is in insert mode. I see that there is a ide constrain that don't let you solve the issue. But anyway +1 to the issue.

**Comment by AlexGirardDev** [comment]
> > @notblam i tried what was sugested a little bit but had some issues getting the ideavim plugin to actualy load within my plugin.
> > Everytime i tried to call the VimPlugin Api i was just get class not found exceptions.
> > I don't have any time right now to dig into this further but i may in the coming weeks.
> 
> I added a comment with the last thing I was trying before I gave up. I too was stuck with the ClassNotFound exception despite everything looking normal and the IDE finding things completely fine.
> 
> I'll be on the lookout for your update :)

I managed to make some progress on this but got stuck again. I have the popup starting in normal mode now but for some reason the modal is just eating 1 hotkey after doing this. so if you want to say delete the item you have selected you have to press d 3 times instead of 2 .

I have a feeling something wierd is going on with dialogWrapper  so i may have to make my own popup controll to get around this but i don't have the time currently.

If you wanted to dig into it some more @notblam the branch is here https://github.com/AlexGirardDev/HarpoonIJ/tree/force_dialog_normal_mode

**Comment by AlexPl292** [comment]
Hi there, I see that some state is not reset during the direct call. However, I'd say that it would be a bit complicated to fix it at the moment.
You can try to pass the esc key directly to the key handler:
```
ExecutionContext.Editor context = VimInjectorKt.injector.getExecutionContextManager().onEditor(IjVimEditorKt.getVim(editorTextField.getEditor()), null);
KeyHandler.getInstance().handleKey(
     IjVimEditorKt.getVim(editorTextField.getEditor()),
     VimInjectorKt.injector.getParser().parseKeys("<ESC>").get(0),
     context
 );
 ```

**Comment by AlexGirardDev** [comment]
That seems to work perfectly, thank you for the help @AlexPl292.

**Comment by AlexGirardDev** [comment]
i have implemented the featuer and should go out with the next release in the next 1-2 days

**Comment by HolbyFPV** [comment]
Awesome work! @AlexGirardDev @AlexPl292 

My workflow is saved ❤️

**Comment by AlexGirardDev** [comment]
Version 1.4 is now availible on the intelij markeplace which has resolved this issue.
