### ISSUE TITLE
<Enter> to navigate to file

### ISSUE THREAD

**Issue by HolbyFPV** [AlexGirardDev/HarpoonIJ#3]
In the neovim version, you can press enter on the dialog window to navigate to whatever file is under the cursor.  I tried implementing this, but only got this far

```java
        editorTextField.registerKeyboardAction(e -> {
            // todo navigate to file underneath cursor
            doCancelAction();
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);
```

If I use a different key, say `VK_T`, this function will trigger.  That's obviously not very ideal, as most harpoon users have never changed their remap from enter.  But I can't get `VK_Enter`, to work at all sadly.

**Comment by AlexGirardDev** [comment]
I ended up digging into this, it seems like the text editor control i'm using is eating the enter key when i have the control set to multi line

the workaround i found was to create a new action to open the selected item.

its a bit of a hack but it seems to be working.
by default it will bind this action to the enter key in normal mode but i have a setting to disable this

you can also bind this to whatever hotkey you wont in your ideavimr

`nnoremap C-k :action SelectHarpoonItem<cr>`

this should be going out in the next release in a couple days

**Comment by HolbyFPV** [comment]
Nice!  Can't wait to be using this.

**Comment by HolbyFPV** [comment]
Used it today, works great.  Thanks again for the work here.
