### ISSUE TITLE
Window starts in insert mode

### ISSUE THREAD

**Issue by Parker7123** [AlexGirardDev/HarpoonIJ#9]
When using ideavim and window with list of files is spawned the editor in the window is in insert mode. For me this is a little bit confusing. For example it requires me to leave insert mode in order to delete a file. Can this be changed so that normal mode is on when the window spawns?

**Comment by AlexGirardDev** [comment]
Can you tell me what version of intelij you are using and the version of your Harpoon plugin?

This feature was added in version 1.4 of HarpoonIJ here #2  but that requires you are using 2023.x+ of Intelij.

**Comment by Parker7123** [comment]
2022 version, I will upgrade it, thank you.

**Comment by AlexGirardDev** [comment]
Actually, this seems to be broken with the latest version of the ideaVim plugin even on , so i am going to reopen this ticket for the time being

**Comment by AlexGirardDev** [comment]
this should be resolved now with v0.1.6 of HarpoonIJ which is now available for download
